In [1]:
%cd ../

/Users/paulb/Desktop/code/research/babi

In [31]:
from data.parsing import capnostream

df = capnostream("data/testing/p1/co2.xlsx")
df

,CO₂ Wave,EtCO₂,RR,SpO₂,PR,EtCO₂ High,EtCO₂ Low,Capnography RR High,Capnography RR Low,No Breath,SpO₂ High,SpO₂ Low,PR High,PR Low,CO₂ Not Available,SpO₂ Not Available,Primary Battery Low,Secondary Battery Low,Events,time
0,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,1,1,0,0,NaN,2025-08-11 08:55:03.000
1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,1,1,0,0,NaN,2025-08-11 08:55:03.050
2,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,1,1,0,0,NaN,2025-08-11 08:55:03.100
3,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,1,1,0,0,NaN,2025-08-11 08:55:03.150
4,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,1,1,0,0,NaN,2025-08-11 08:55:03.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45496,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,1,1,0,0,NaN,2025-08-11 09:32:57.800
45497,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,1,1,0,0,NaN,2025-08-11 09:32:57.850
45498,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,1,1,0,0,NaN,2025-08-11 09:32:57.900
45499,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,1,1,0,0,NaN,2025-08-11 09:32:57.950
45500,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,1,1,0,0,NaN,2025-08-11 09:32:58.000

In [9]:
import os
from data.parsing import motion

motions = set([os.path.join("data/testing/p1", m) for m in os.listdir("data/testing/p1") if m.endswith(".tsv")])

df = motion(motions)
df

,AMid X,AMid Y,AMid Z,BMid X,BMid Y,BMid Z,CMid X,CMid Y,CMid Z,DMid X,...,FL1 Z,FR1 X,FR1 Y,FR1 Z,EL2 X,EL2 Y,EL2 Z,ER2 X,ER2 Y,ER2 Z
2025-08-11 09:13:06.541,486.743,643.981,210.229,462.912,661.867,212.760,443.536,681.709,216.556,421.662,...,208.098,406.935,753.423,199.081,365.281,658.554,197.110,434.155,760.941,185.234
2025-08-11 09:13:06.551,486.762,643.977,210.204,462.984,661.848,212.810,443.539,681.734,216.582,421.686,...,208.085,406.940,753.389,199.033,365.292,658.553,197.111,434.160,760.926,185.169
2025-08-11 09:13:06.561,486.799,643.959,210.179,462.983,661.837,212.817,443.549,681.722,216.577,421.687,...,208.018,406.972,753.371,198.978,365.309,658.579,197.062,434.144,760.923,185.177
2025-08-11 09:13:06.571,486.781,643.950,210.123,462.976,661.836,212.817,443.550,681.722,216.561,421.724,...,207.970,406.967,753.374,198.929,365.326,658.585,197.014,434.151,760.893,185.150
2025-08-11 09:13:06.581,486.753,643.937,210.057,462.976,661.833,212.796,443.543,681.720,216.539,421.764,...,207.938,406.950,753.370,198.877,365.340,658.582,196.970,434.157,760.846,185.139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-08-11 09:37:35.351,379.274,631.876,211.055,356.316,654.837,190.177,NaN,NaN,NaN,341.795,...,NaN,NaN,NaN,NaN,290.978,671.274,130.441,404.924,732.597,145.251
2025-08-11 09:37:35.361,388.024,632.758,220.854,356.277,654.827,190.321,NaN,NaN,NaN,331.157,...,NaN,NaN,NaN,NaN,290.977,671.300,130.417,404.905,732.634,145.222
2025-08-11 09:37:35.371,401.665,630.754,236.496,356.132,654.852,190.238,NaN,NaN,NaN,333.213,...,NaN,NaN,NaN,NaN,290.956,671.301,130.376,404.922,732.668,145.247
2025-08-11 09:37:35.381,421.869,623.993,256.653,356.112,654.835,190.329,NaN,NaN,NaN,333.802,...,NaN,NaN,NaN,NaN,290.946,671.300,130.393,404.884,732.662,145.252
2025-08-11 09:37:35.391,436.003,622.157,273.211,356.051,654.834,190.440,NaN,NaN,NaN,334.428,...,NaN,NaN,NaN,NaN,290.924,671.270,130.355,404.872,732.647,145.272

In [10]:
import pipeline

capnostream_data, labeled_motion, capno2 = pipeline.execute(os.path.join("data", "testing", "p1"), offset=360)
capno2

/Users/paulb/Desktop/code/research/babi/data/parsing.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  from globals import constants

45501 45501

TypeError: <class 'datetime.time'> is not convertible to datetime, at position 0